### ISSUE TITLE
Connect Product screen to Redux

### ISSUE THREAD

**Issue by RITESHKUMAR10** [RITESHKUMAR10/Ritesh-Mart#1]
I have an error like Request failed with status code 404. I have check twice time step by step from resource link and exactly same from my point of view but unable to resolve the error.Please help in this.

**Comment by basir** [comment]
in which api you get this error?
screenshot of the error in the chrome dev tools
terminal log for backend
terminal log for frontend

**Comment by RITESHKUMAR10** [comment]
![Screenshot (69)](https://user-images.githubusercontent.com/43420487/86341780-62eaba80-bc74-11ea-87f8-97abeac29ea3.png)
![Screenshot (70)](https://user-images.githubusercontent.com/43420487/86341792-654d1480-bc74-11ea-9e6d-6ce7f05861dd.png)
![Screenshot (72)](https://user-images.githubusercontent.com/43420487/86341795-667e4180-bc74-11ea-8a1d-a3c8b7089c92.png)
![Screenshot (73)](https://user-images.githubusercontent.com/43420487/86341801-67af6e80-bc74-11ea-887b-244254e62f9f.png)
![Screenshot (76)](https://user-images.githubusercontent.com/43420487/86341810-68e09b80-bc74-11ea-8b26-2acecad46060.png)

**Comment by RITESHKUMAR10** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/43420487/86342194-e3a9b680-bc74-11ea-9e0d-c616c8215c8d.png)

NOTE:After clicking on product page i am getting error like Request failed with status code 404.

**Comment by RITESHKUMAR10** [comment]
Please fix this error sir i am not able to move forward because of this stuck.

**Comment by RITESHKUMAR10** [comment]
Please fix the error sir, i am waiting for you to fix the error

**Comment by basir** [comment]
I can see any error in your code. install skype on your computer and keep your error open and send me a message over skype to basir.jafarzadeh

**Comment by RITESHKUMAR10** [comment]
i have installed and also sent you a message .As a urgent basis please fix my error

**Comment by RITESHKUMAR10** [comment]
finally issue is resolved
